version: '2'
services:
  hyperstream:
    build: HyperStream-tutorials
    links:
      - "hyperstream-mongo:mongo"
    ports:
      - "8888:8888"
  hyperstream-mongo:
    build: HyperStream-mongo
#    volumes:
#      - ~/hyperstream_mongodb:/home/jovyan/hyperstream
  hyperstream-viewer:
    build: HyperStream-viewer
    ports:
      - "5000:5000"

