version: '2'
services:
  hyperstream:
    build: HyperStream
    links:
      - "hyperstream-mongo:mongo"
      - "hyperstream-mqtt:mqtt"
  hyperstream-mongo:
    build: HyperStream-mongo
  hyperstream-mqtt:
    image: "toke/mosquitto"
  hyperstream-viewer:
    build: HyperStream-viewer
    ports:
      - "5000:5000"
